### ISSUE TITLE
CLI Webhook HTTPListener does not receive traffic from NGROK

### ISSUE THREAD

**Issue by bporter125** [iovation/launchkey-dotnet#19]
Upon running service-auth-webhook the console will display:
Webhook: Starting HTTP listener.
Webhook: Waiting for a request ...

Upon responding to the auth, the socket is never hit when using a proxy like NGROK. Testing the same flow on a Windows VM works fine, so I suspect the HTTPListener isn't playing nicely on Mac and potentially Linux (unconfirmed).

**Comment by aenglander** [comment]
The SDK and unit test projects are the only pieces compatible with dotnet core. This is so that we can build the DLL for the targets. I am changing this to a feature request and rewording.

**Comment by aenglander** [comment]
This was resolved with the recent changes for the 3.4.0 release that allow the netcore20 target for the example CLI.
